"""create_pii_settings_table

Revision ID: e31ba775f28a
Revises: 16a43009c50b
Create Date: 2025-11-04 01:36:16.558953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31ba775f28a'
down_revision: Union[str, Sequence[str], None] = '16a43009c50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='PII 엔티티 타입 (PERSON, PHONE_NUM, EMAIL 등)'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='탐지 활성화 여부'),
    sa.Column('threshold', sa.Integer(), nullable=False, comment='탐지 민감도 (0-100, 이 값 이상일 때만 탐지)'),
    sa.Column('description', sa.Text(), nullable=True, comment='PII 타입 설명'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_settings_entity_type'), 'pii_settings', ['entity_type'], unique=True)
    op.create_index(op.f('ix_pii_settings_id'), 'pii_settings', ['id'], unique=False)
    # ### end Alembic commands ###

    # Insert default PII settings (모든 타입 활성화, threshold=59)
    op.execute("""
        INSERT INTO pii_settings (entity_type, enabled, threshold, description, created_at, updated_at) VALUES
        ('PERSON', true, 59, '사람 이름 (예: 홍길동, John Doe)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('PHONE_NUM', true, 59, '전화번호 (예: 010-1234-5678, 02-123-4567)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('EMAIL', true, 59, '이메일 주소 (예: user@example.com)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('ADDRESS', true, 59, '주소 (예: 서울시 강남구 테헤란로 123)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('ID_NUM', true, 59, '주민등록번호 및 기타 식별번호', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('CREDIT_CARD', true, 59, '신용카드 번호', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('ACCOUNT', true, 59, '계좌번호', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('ORG', true, 59, '조직/회사명', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('LOCATION', true, 59, '지명/위치', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('DATE', true, 59, '날짜 정보 (생년월일 등)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pii_settings_id'), table_name='pii_settings')
    op.drop_index(op.f('ix_pii_settings_entity_type'), table_name='pii_settings')
    op.drop_table('pii_settings')
    # ### end Alembic commands ###
